title: MetalFury DevBlog
description: A site using the Modernist theme with custom navigation
baseurl: "" # leave blank for root
url: "https://derinzed.github.io" 

# Enable remote theme
remote_theme: pages-themes/modernist@v0.2.0

# Optional: exclude certain folders/files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Markdown engine
markdown: kramdown

# Plugins (required for remote_theme on GitHub Pages)
plugins:
  - jekyll-remote-theme
